version: '3'
services:
  jenkins:
    image: bitnami/jenkins:latest
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - JENKINS_USERNAME=cyacarini
      - JENKINS_PASSWORD=P@ssw0rd
    volumes:
      - jenkins_data:/bitnami
volumes:
  jenkins_data:
    driver: local
